CREATE TABLE Pizzas(
    pizzas_id int GENERATED BY DEFAULT AS IDENTITY primary key,
    pizzas_name varchar(20),
    pizzas_price double,
    pizzas_type int	
);

INSERT INTO Pizzas (pizzas_name, pizzas_price, pizzas_type) VALUES ('Big Meat Pizza', 450.00, 2)
INSERT INTO Pizzas (pizzas_name, pizzas_price, pizzas_type) VALUES ('Big Sea Pizza', 500.00, 1)


CREATE TABLE Orders(
    orders_id int GENERATED BY DEFAULT AS IDENTITY primary key,
    orders_name varchar(20),
    orders_date date,
    orders_price double
);

INSERT INTO Orders (orders_name, orders_date, orders_price) VALUES ('Order1', '2008-08-22', 0.0)
INSERT INTO Orders (orders_name, orders_date, orders_price) VALUES ('Order2', '2015-10-15', 0.0)


CREATE TABLE Pizzasinorders(
	order_id int FOREIGN KEY REFERENCES Orders(orders_id),
	pizza_id int FOREIGN KEY REFERENCES Pizzas(pizzas_id),	
);

INSERT INTO Pizzasinorders (order_id, pizza_id) VALUES (0, 0)
INSERT INTO Pizzasinorders (order_id, pizza_id) VALUES (0, 1)