CREATE TABLE Addresses(
	addresses_id int GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL primary key,
	postal_code varchar(20),
	city varchar(20),
	street varchar(30),
	bld varchar(10),
	apt varchar(10)
);

CREATE TABLE Clients(
	clients_id int GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL primary key,
	clients_name varchar(50),
	address_id int FOREIGN KEY REFERENCES Addresses(addresses_id)	
);

CREATE TABLE Pizzas(
    pizzas_id int GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL primary key,
    pizzas_name varchar(20),
    pizzas_price double,
    pizzas_type int	
);

CREATE TABLE Orderstatuses(
	order_statuses_id int GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL primary key,
	order_statuses_name varchar(15)
);

CREATE TABLE Orders(
    orders_id int GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL primary key,
    orders_name varchar(20),
    orders_date date,
    orders_price double,
    orders_status_id int FOREIGN KEY REFERENCES Orderstatuses(order_statuses_id),
    client_id int FOREIGN KEY REFERENCES Clients(clients_id)
);

CREATE TABLE Pizzasinorders(
	pizzas_in_orders_id int GENERATED BY DEFAULT AS IDENTITY 
                                         (START WITH 1, INCREMENT BY 1) NOT NULL primary key,
	order_id int FOREIGN KEY REFERENCES Orders(orders_id),
	pizza_id int FOREIGN KEY REFERENCES Pizzas(pizzas_id),
	quantity int
);